#!/bin/sh

export NAME=extr

export COOB=$HOME/coob
export COOBDB=$COOB/adm
export BACKUPDIR=$COOB/backup
export LOGDIR=$COOB/log
export FGENDIR=$COOB/fgen

export TCL=$HOME/tcl
export BITMAPDIR=$TCL/bitmap

export SOURCEDIR=/mnt/cc-x/cc-x3/coob/lib/extr
export LIBDIR=/mnt/cc-x/cc-x3/coob/lib/utils

export ORBIT_DIR=$COOB/orbit

export XMAD_HOME=$COOB/lib/xmad
export MODELLDIR=$COOB/lib/modell
export COSMO_BIN=$HOME/coob/bin
export COSMO_SRC=$HOME/coob/lib
export PGHOST=dbserver
export PGUSER=operator

export PATH=$PATH:/mnt/cc-x/cc-x3/coob/bin/Linux

pgwish -f $SOURCEDIR/$NAME.tcl ${1+"$@"}
